# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gLX4j3q5qXo31cgci4tcgleA129cOyVM
"""

import numpy as np
import math

def runge_kutta(y,x,dx,f):
  
  "f is derivative of y(t)"

  k1 = dx * f(y, t)
  k2 = dx * f(y + 0.5 * k1, x + 0.5 * dx)
  k3 = dx * f(y + 0.5 * k2, x + 0.5 * dx)
  k4 = dx * f(y + k3, x + dx)

  return y+(k1 + 2 * k2 + 2 * k3 + k4) / 6

E0 = 1
S0 = 10
K1, K2, K3 = 100,600, 150



